module.exports = {
    STORE_KEY: 'a56z0fzrNpl^2',
    screen :'',
    time : 0,
    BASE_URL: 'http://139.59.76.223/mehwar_app/admin/api/users/',
    //BASE_URL: 'http://www.thenewsmen.co.in/newsmentest/admin/api/',
    
    profileImage:'',
    lang:'',
    name:'',
    name2:'',
    email:'',
    email2:'',
    phone:'',
    phone2:'',
    password:'',
    flag:'',
    otp:'',
    otp2:'',
    userID:'',
    proimage:'',
    proimage2:'',
    token:'',
    postID:'',
    eventData:'',
    newsData:'',
    flatlist:'',
    editImage:'',
    forgetOtp:'',
    mobforgo:'',
    bookingid:2,
    myname:'',
    firetoken:'',
    chatstatus:'',
    chat_g_id:'',
    dimage:'',
    channel:'',
    
    COLOR: {
        ORANGE: '#C50',
        DARKBLUE: '#0F3274',
        LIGHTBLUE: '#6EA8DA',
        DARKGRAY: '#999',
    },
};